# Generated by Django 2.2.3 on 2019-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0101_remove_null_sort_order")]

    operations = [
        migrations.AlterField(
            model_name="attributeproduct",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="attributevariant",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="collectionproduct",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
