# Generated by Django 2.2.3 on 2019-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("menu", "0015_remove_null_sort_order")]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        )
    ]
