# Generated by Django 2.0.3 on 2018-06-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('order', '0047_order_line_name_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='variant',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_provider_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_provider_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
