name: Pytest

on: [pull_request]

env:
  QUERIES_RESULTS_PATH: /tmp/queries-results.json

jobs:
  build:
    runs-on: ubuntu-20.04
    container: python:3.8

    steps:
    - uses: actions/checkout@v2

    - name: Dummy Dump
      run: echo "hello world" > ${QUERIES_RESULTS_PATH}

    - uses: NyanKiyoshi/pytest-django-queries-ci-tools@github-action-test
      with:
        query_raw_dump_path: ${{ env.QUERIES_RESULTS_PATH }}
        diff_endpoint: "https://example.com/diff"
        diff_results_base_url: "https://example.com/diffs"
        upload_endpoint: ${{ secrets.UPLOAD_ENDPOINT }}
        upload_secret_key: ${{ secrets.SECRET_UPLOAD_KEY }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
