name: Pytest

on: [pull_request]

env:
  QUERIES_RESULTS_PATH: ./queries-results.json

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Test
      run: |
        python -Im pip install pytest-django-queries
        cat > ./queries-results.json <<EOF
        {"saleor.graphql.account.tests.benchmark.test_account": {"test_staff_create": {
            "query-count": 1,
            "duplicates": 0
        }}}
        EOF

    - uses: NyanKiyoshi/pytest-django-queries-ci-tools@github-action-test
      with:
        query_raw_dump_path: ${{ env.QUERIES_RESULTS_PATH }}
        diff_endpoint: "https://rn4nfofmgc.execute-api.us-east-1.amazonaws.com/default/saleor-db-queries-bot-diff"
        diff_results_base_url: "https://dtab784j47g1o.cloudfront.net"
        upload_endpoint: ${{ secrets.UPLOAD_ENDPOINT }}
        upload_secret_key: ${{ secrets.SECRET_UPLOAD_KEY }}
