name: Pytest

on: [pull_request]

env:
  QUERIES_RESULTS_PATH: /tmp/queries-results.json

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Test
      run: |
        echo '***'
        env
        echo '***'
        command -v python
